# Generated by Django 5.0.1 on 2024-01-26 22:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='ingrese el nombre', max_length=50)),
                ('apellido', models.CharField(help_text='ingrese el apellido', max_length=50)),
                ('fechaNac', models.DateField(blank=True, null=True)),
                ('fechaDeceso', models.DateField(blank=True, null=True, verbose_name='Fallecido')),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ingrese el nombre del gènero', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('resumen', models.CharField(help_text='ingrese un resumen del libro', max_length=1000)),
                ('isbn', models.CharField(help_text='13 caracteres <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>', max_length=13, verbose_name='ISBN')),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.autor')),
                ('genero', models.ManyToManyField(help_text='seleccione un genero (o varios) para el libro', to='catalogo.genero')),
            ],
        ),
        migrations.CreateModel(
            name='Ejemplar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID unico para este libro particular en toda la biblioteca', primary_key=True, serialize=False)),
                ('fechaDeDevolucion', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, choices=[('m', 'en mantenimiento'), ('p', 'prestado'), ('d', 'disponible'), ('r', 'reservado')], default='d', help_text='Disponibilidad del ejemplar', max_length=1)),
                ('libro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.libro')),
            ],
            options={
                'ordering': ['fechaDeDevolucion'],
            },
        ),
    ]
