# Generated by Django 5.0.1 on 2024-02-07 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_idioma'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='libro/'),
        ),
    ]
