# Generated by Django 5.0.1 on 2024-02-19 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_alter_autor_imagen_alter_libro_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'ordering': ['apellido', 'nombre']},
        ),
        migrations.AlterModelOptions(
            name='libro',
            options={'ordering': ['titulo']},
        ),
    ]
