# Generated by Django 5.0.1 on 2024-02-28 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_alter_autor_options_alter_libro_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='imagen',
            field=models.ImageField(null=True, upload_to='media/autor'),
        ),
    ]
